---
- hosts: pis
  remote_user: pi
  # als root ausführen
  become: yes

  vars:
    # Nutzername für den neuen Nutzer
    new_user: exam
    # Dateiname der Datei, die transferiert werden soll
    datei_abgabe: abgabe.tar.gz

  tasks:
    # Verzeichnisse werden (noch) nicht unterstützt.
    - name: Abgabe einsammeln
      fetch: src="/home/{{ new_user  }}/{{ datei_abgabe }}" dest=fetched
