---
- hosts: pis
  remote_user: pi
  # Befehle als root ausführen
  become: yes

  vars:
    # Nutzername für den neuen Nutzer
    new_user: exam
    # Dateiname der Datei, die transferiert werden soll
    datei_tansfer: uhrzeit.txt

  tasks:
    - name: nano installieren
      apt: name=nano

    - name: mc installieren
      apt: name=mc

    # Wird für synchronize gebraucht
    - name: rsync installieren
      apt: name=rsync

    - name: Testuser anlegen
      # Passwort 123456 generiert mit mkpasswd --method=sha-512
      user: 
        name="{{ new_user }}"
        password="$6$QIMo8rBLzR9a7s$BJH7y45WU78KmQwk9nf49.rdCgpzbXQB/bAJLlw2PF4PvlCfFSXKoaX4UzD.VC0BdqkoqZiOOepo9k627HwmD0"
        shell=/bin/bash

    - name: Rechte im Homeverzeichnis beschneiden
      shell: chmod go-x /home/*

    - name: Lokale Dateien verteilen
      copy: src="{{ datei_tansfer }}" dest="/home/{{ new_user }}/"

    - name: Besitzer der transferierten Datei anpassen
      file: 
        path="/home/{{ new_user }}/{{ datei_tansfer }}"
        owner="{{ new_user }}" 
