wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 32, 32]
    rows: [10, 10, 10, 10, 10, 10]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        - Berlin: "Europe/Berlin"
        - London: "Europe/London"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks"
      type: "clocks"
    feedreader:
      title: "TBS1-News"
      enabled: true
      feeds:
      - "https://tbs1.de/jcms/index.php?format=feed&type=rss"
      feedLimit: 10
      position:
        top: 0
        left: 1
        width: 2
        height: 1
      updateInterval: 14400
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      refreshInterval: 150
    corona:
      title: "Corona"
      type: cmdrunner
      args: [""]
      cmd: "corona2.py"
      enabled: true
      refreshInterval: 30
      position:
        top: 2
        left: 0
        height: 1
        width: 1
    ebike:
      title: "Ebike-Garage Belegung"
      type: cmdrunner
      args: [""]
      cmd: "ebike_status.py"
      enabled: true
      refreshInterval: 30
      position:
        top: 1
        left: 2
        height: 1
        width: 2
    ebike_sensoren:
      title: "Ebike-Garage Sensoren"
      type: cmdrunner
      args: [""]
      cmd: "ebike_tbs1_sensoren.py"
      enabled: true
      refreshInterval: 30
      position:
        top: 2
        left: 2
        height: 1
        width: 2
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 8
      repositories:
      - "/home/pintman/proj/physical_computing"
      - "/home/pintman/proj/software-101"
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 5
      showCPU: true
      showMem: true
      showSwp: true
    bees:
      title: "Bienen"
      type: cmdrunner
      args: [""]
      cmd: "tbs1_bees.sh"
      enabled: true
      refreshInterval: 60
      position:
        top: 3
        left: 2
        height: 1
        width: 2
    freifunk:
      title: "Freifunk"
      type: cmdrunner
      args: [""]
      cmd: "freifunk_node.py"
      enabled: true
      refreshInterval: 60
      position:
        top: 4
        left: 2
        height: 2
        width: 2
 
